### ISSUE TITLE
como se puede hacer para poder añadir nuevas notas desde el navegador de internet

### ISSUE THREAD

**Issue by runtimevic** [danmatlam/calendario-redux-sagas-tuto#1]
Hola, muy buen trabajo, enhorabuena por todo
No se continuar el proyecto para poder añadir nuevas notas desde el navegador de internet, 
No quiero que salgan notas constantes cargadas, si no poder añadirlas desde el navegador y al salir y volver a entrar que se vuelvan a ver las ultimas notas guardadas.
un saludo, Víctor.

**Comment by danmatlam** [comment]
- Hola, terminaste el ejercicio en youtube? Si es así me alegro. 
- Bien redux y react son netamente frontend eso debe estar bien claro. Si quieres guardar datos  (persistencia) debes usar un lenguaje de backend.
- Si  ya dominas un lenguaje de backend. Puedes hacer la subscripción a un servicio web en el archivo de acciones.

**Comment by danmatlam** [comment]
- Hola, terminaste el ejercicio en youtube? Si es así me alegro.
- Bien redux y react son netamente frontend eso debe estar bien claro. Si quieres guardar datos (persistencia) debes usar un lenguaje de backend.
- Si ya dominas un lenguaje de backend. Puedes hacer la subscripción a un servicio web en el archivo de acciones.

**Comment by runtimevic** [comment]
si esta claro, sabes de algún ejemplo con todo react, redux y por ejemplo que en la parte de backend se puedan guardar en un fichero xml o en json todas las notas o en una base de datos o de cualquier otra forma??.
